### ISSUE TITLE
Error: Running FINN in Docker

### ISSUE THREAD

**Issue by lloo099** [Xilinx/finn#395]
Hi, as I already installed Vivado HLS 2018.3 in Ubuntu 18.04, when I try to bash ./run_docker.sh in terminal. There are some errors about Vivado_Path, and I don't know how to set the Path in ubuntu, Could you help me with that?

Errors :
Please set the VIVADO_PATH that contains the path to your Vivado installation directory.
FINN functionality depending on Vivado or Vivado HLS will not be available.
Please set the PYNQ_IP env.var. to enable PYNQ deployment tests.
Please set the VITIS_PATH that contains the path to your Vitis installation directory.
FINN functionality depending on Vitis will not be available.
*****
Obtaining file:///workspace/finn
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/workspace/finn/setup.py'"'"'; __file__='"'"'/workspace/finn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vcxelnw6
         cwd: /workspace/finn/
    Complete output (29 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/workspace/finn/setup.py", line 50, in <module>
        setup(use_pyscaffold=True)
      File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 423, in __init__
        _Distribution.__init__(self, {
      File "/opt/conda/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 695, in finalize_options
        ep(self)
      File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/workspace/finn/.eggs/PyScaffold-3.2.3-py3.8.egg/pyscaffold/integration.py", line 105, in pyscaffold_keyword
        version_keyword(dist, keyword, setuptools_scm_config(value))
      File "/workspace/finn/.eggs/PyScaffold-3.2.3-py3.8.egg/pyscaffold/contrib/setuptools_scm/integration.py", line 17, in version_keyword
        dist.metadata.version = get_version(**value)
      File "/workspace/finn/.eggs/PyScaffold-3.2.3-py3.8.egg/pyscaffold/contrib/setuptools_scm/__init__.py", line 150, in get_version
        parsed_version = _do_parse(config)
      File "/workspace/finn/.eggs/PyScaffold-3.2.3-py3.8.egg/pyscaffold/contrib/setuptools_scm/__init__.py", line 105, in _do_parse
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for '/workspace/finn'.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
bash: /settings64.sh: No such file or directory

Thanks,

**Comment by fpjentzsch** [comment]
Moved to existing discussion: https://github.com/Xilinx/finn/discussions/387
