### ISSUE TITLE
AttributeError: 'StreamingFIFO' object has no attribute 'get_output_datatype' in step_synthesize_bitfile 

### ISSUE THREAD

**Issue by mgehre-amd** [Xilinx/finn#665]
## Prerequisites
Please make sure to check off these prerequisites before submitting a bug report.
- [x] Test that the bug appears on the current version of the dev-branch. Make sure to include the commit hash of the commit you checked out.
- [x] Check that the issue hasn't already been reported, by checking the currently open issues.
- [x] If there are steps to reproduce the problem, make sure to write them down below.
- [x] If relevant, please include the ONNX files, which were created directly before and/or after the bug.

## Quick summary
I'm getting
```
Running step: step_synthesize_bitfile [12/14]
Traceback (most recent call last):
  File "/scratch/finn/src/finn/builder/build_dataflow.py", line 166, in build_dataflow_cfg
    model = transform_step(model, cfg)
  File "/scratch/finn/src/finn/builder/build_dataflow_steps.py", line 633, in step_synthesize_bitfile
    model = model.transform(
  File "/scratch/finn/deps/qonnx/src/qonnx/core/modelwrapper.py", line 140, in transform
    (transformed_model, model_was_changed) = transformation.apply(transformed_model)
  File "/scratch/finn/src/finn/transformation/fpgadataflow/make_zynq_proj.py", line 339, in apply
    model = model.transform(trn)
  File "/scratch/finn/deps/qonnx/src/qonnx/core/modelwrapper.py", line 140, in transform
    (transformed_model, model_was_changed) = transformation.apply(transformed_model)
  File "/scratch/finn/src/finn/transformation/fpgadataflow/insert_dwc.py", line 89, in apply
    dtype = n0.get_output_datatype()
AttributeError: 'StreamingFIFO' object has no attribute 'get_output_datatype'
```
when running
```
export FINN_XILINX_PATH=/path/to/2022.1
export FINN_XILINX_VERSION=2022.1
./run-docker.sh build_custom ../finn-examples/build/mobilenet-v1
```
### Details
I'm on dev branch
```
commit 09bec2fe (HEAD -> dev, origin/dev)
Merge: a13faced ffa1b3db
Author: auphelia <56755897+auphelia@users.noreply.github.com>
Date:   Fri Jul 29 15:33:07 2022 +0100

    Merge pull request #647 from Xilinx/feature/builder_verbose

    [Build] New flag "verbose" to control build_dataflow verbosity
```

### Expected behavior
No error

### Actual behavior
See above

**Comment by auphelia** [comment]
Hi @mgehre-amd , thanks for raising this issue. It is addressed in [PR-705](https://github.com/Xilinx/finn/pull/705) and `dev` is now up-to-date with the changes. I will close this issue.
